docs: Clarify NGC sync response packet protocol
TokTok/hs-toxcore pull request #210
Opened 2022-04-28 15:26 UTC by JFreegman

2022-05-02 16:57 UTC, iphydf approved these changes

2022-05-07 17:19 UTC, zoff99 requested changes

2022-05-07 17:19 UTC, zoff99 commented on src/Network/Tox/Application/GroupChatsPackets.lhs
> +This packet is used to to send arbitrary data to the group. It may be
```This packet is used to to send```
word "to" is double

2022-05-07 17:41 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/hs-toxcore/210)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @zoff99)

___
*[`src/Network/Tox/Application/GroupChatsPackets.lhs` line 285 at r1](https://reviewable.io/reviews/toktok/hs-toxcore/210#-N0klz5XKt_ECOZQIpvr-r1-285:-N1UbCLs1kpnDpvxSdjA:b-896fix) ([raw file](https://github.com/toktok/hs-toxcore/blob/49604a59bbbfef8dd4884624e132a95b36e3689f/src/Network/Tox/Application/GroupChatsPackets.lhs#L285)):*
<details><summary><i>Previously, zoff99 (Zoff) wrote…</i></summary><blockquote>

```This packet is used to to send```
word "to" is double
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-07 17:53 UTC, zoff99 approved these changes

2023-09-01 09:52 UTC, iphydf approved these changes

2023-11-07 23:00 UTC, merged